configfile: "config/config.yaml"
import re

def sanitize_filename(name):
    return re.sub(r'[^A-Za-z0-9_]', '_', name)

organisms = config["organisms"]
ks = config["k"]
results_directories = expand("results/k{k}/{organism}", k=ks, organism=organisms)
paths = list(config["paths"].values())

rule all:
    input:
        expand("results/k{k}/{organism}/.results_directories_created", k=ks, organism=organisms)

rule create_base_directories:
    output:
        ".directories_created"
    params:
        dirs = paths
    shell:
        """
        mkdir -p {params.dirs}
        touch {output}
        """
rule create_results_directories:
    input:
        ".directories_created"
    output:
        expand("results/k{k}/{organism}/.results_directories_created", k=ks, organism=organisms)
    params:
        dirs = results_directories
    shell:
        """
        mkdir -p {params.dirs}
        touch {output}
        """
rule check_genome_integrity:
    input:
        expand("results/k{k}/{organism}/.results_directories_created", k=ks, organism=organisms)
    output: