name: nulloretriever
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12  
  - snakemake>=8.0
  - pip
  - pip:
      - biopython==1.85
      - bitarray==3.8.1
      - matplotlib==3.11.0
      - numpy==2.5.1
      - pandas==3.0.3
      - pyyaml==6.0.3
      - requests==2.34.2
      - scipy==1.18.0
      - seaborn==0.13.2
      - psutil==7.2.2
      - filelock==3.29.5  
