organismos:
- Candida_anglica
- Candida_zeylanoides
- Allantophomopsis_cytisporea
- Allantophomopsis_lycopodina
- Alternaria_brassicae
- Alternaria_solani
- Annulohypoxylon_stygium
- Anthracocystis_panici-leucophaei
- Apiotrichum_mycotoxinovorans
- Ascochyta_rabiei
- Aspergillus_felis
- Aspergillus_flavus
- Aspergillus_sojae
- Blastobotrys_mucifer
- Botrytis_cinerea_B05_10
- Botrytis_fabae
- Brettanomyces_bruxellensis
- Brettanomyces_nanus
- Calonectria_ilicicola
- Candidozyma_auris
- Candidozyma_vulturna
- Cercospora_beticola
- Cercospora_sojina
- Chrysoporthe_puriensis
- Clonostachys_rosea
- Coccidioides_posadasii_str._Silveira
- Colletotrichum_destructivum
- Colletotrichum_gigasporum
- Colletotrichum_lini
- Colletotrichum_lupini
- Cryptococcus_bacillisporus_CA1280
- Cryptococcus_decagattii
- Cryptococcus_depauperatus_CBS_7841
- Cyberlindnera_fabianii
- Didymella_pinodella
- Diutina_catenulata
- Epichloe_amarillans
- Epichloe_baconii
- Epichloe_brachyelytri
- Epichloe_bromicola
- Epichloe_elymi
- Epichloe_festucae_Fl1
- Epichloe_gansuensis
- Epichloe_glyceriae
- Epichloe_scottii
- Epichloe_typhina_subsp._poae
- Eremothecium_sinecaudum
- Exophiala_lecanii-corni
- Fulvia_fulva
- Fusarium_acuminatum
- Fusarium_asiaticum
- Fusarium_avenaceum
- Fusarium_culmorum
- Fusarium_falciforme
- Fusarium_meridionale
- Fusarium_oxysporum_Fo47
- Fusarium_phialophorum
- Fusarium_sambucinum
- Hanseniaspora_guilliermondii
- Hanseniaspora_menglaensis
- Hanseniaspora_meyeri
- Hanseniaspora_mollemarum
- Immersiporthe_knoxdaviesiana
- Kluyveromyces_lactis
- Kluyveromyces_marxianus_DMKU3-1042
- Kwoniella_bestiolae_CBS_10118
- Kwoniella_botswanensis
- Kwoniella_dejecticola_CBS_10117
- Kwoniella_dendrophila_CBS_6074
- Kwoniella_europaea_PYCC6329
- Kwoniella_pini_CBS_10737
- Kwoniella_shandongensis
- Kwoniella_shivajii
- Lodderomyces_beijingensis
- Lodderomyces_elongisporus
- Lyophyllum_decastes
- Malassezia_arunalokei
- Malassezia_brasiliensis
- Malassezia_caprae
- Malassezia_cuniculi
- Malassezia_equina
- Malassezia_japonica
- Malassezia_nana
- Malassezia_obtusa
- Malassezia_psittaci
- Malassezia_restricta
- Malassezia_vespertilionis
- Malassezia_yamatoensis
- Marquandomyces_marquandii
- Metarhizium_brunneum
- Monosporozyma_servazzii
- Monosporozyma_unispora
- Nannizziopsis_arthrosporioides
- Neofusicoccum_parvum
- Peltaster_fructicola
- Penicillium_coffeae
- Penicillium_fuscoglaucum
- Penicillium_herquei
- Pichia_kudriavzevii
- Pichia_terricola
- Pneumocystis_wakefieldiae
- Purpureocillium_takamizusanense
- Pyrenophora_teres_f._maculata
- Pyricularia_penniseti
- Remersonia_thermophila
- Rhodotorula_mucilaginosa
- Saccharomyces_bayanus
- Saccharomyces_cerevisiae_S288C
- Saccharomyces_uvarum
- Salmacisia_buchloeana
- Septoria_linicola
- Sordaria_macrospora
- Sporisorium_scitamineum
- Sugiyamaella_lignohabitans
- Talaromyces_funiculosus
- Talaromyces_marneffei
- Talaromyces_pinophilus
- Talaromyces_purpureogenus
- Thermothelomyces_thermophilus_ATCC_42464
- Thermothielavioides_terrestris_NRRL_8126
- Torulaspora_globosa
- Trichoderma_asperellum
- Trichoderma_atroviride
- Trichoderma_simmonsii
- Tricholoma_bakamatsutake
- Trichothecium_roseum
- Ustilaginoidea_virens
- Venturia_effusa
- Yamadazyma_tenuis
- Yarrowia_lipolytica
- Zygotorulaspora_mrakii
k: 12
